# Generated by Django 4.2.6 on 2023-12-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('error_message', models.CharField(max_length=100)),
            ],
        ),
    ]
