# Generated by Django 4.2.6 on 2023-12-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0002_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='error_message',
        ),
    ]
