# Generated by Django 4.2.6 on 2023-12-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0003_remove_program_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='view_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
