# Generated by Django 4.2.6 on 2023-12-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0004_program_view_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='hw_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
