# Generated by Django 5.0 on 2023-12-10 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0005_program_hw_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('similarity_ratio', models.FloatField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dal.program')),
            ],
        ),
    ]
