# Generated by Django 5.0 on 2023-12-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0006_comparefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparefile',
            name='similarity_ratio',
            field=models.CharField(max_length=100),
        ),
    ]
