# Generated by Django 5.0 on 2023-12-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dal', '0007_alter_comparefile_similarity_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparefile',
            name='view_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
